name: 'cross'
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  cross:
    name: Cross
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: cargo init
      run: cargo init
    - name: cargo add libc
      run: cargo add libc
    - name: Install cross
      run: cargo install cross
    - name: Install armv7-unknown-linux-gnueabihf Rust target
      run: rustup target add armv7-unknown-linux-gnueabihf
    - name: Run
      run: cross run --verbose --target armv7-unknown-linux-gnueabihf
